name: Build and deploy Node.js app to Azure Web App - milmyeon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install
        run: npm install

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "milmyeon"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5bde91d49f9044ca9ee3067d05f7cc5b }}

      - name: Start Node.js application
        run: |
          cd $GITHUB_WORKSPACE
          node index.js
